apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-hub-nats-flapi-configmap
  namespace: dev-hub-nats-flapi
data:
  nats.conf: |
    pid_file: "/var/run/nats/nats.pid"
    host: "0.0.0.0"
    port: 4222
    debug: true
    trace: true
    logtime: true

    accounts: {
      admin: {
        jetstream: enabled
        users: [
          { nkey: "UBYXUQX2MZNGMKZR5XGKOMFRNQGIHUSS43BDM7ZXUKGZ355U75LAHQQZ" }
        ]
      }
    }

    jetstream: {
      max_mem: 10GB,
      max_file: 1500GB,
      store_dir: "/data/nats"
    }

    tls: {
      cert_file: "/etc/nats/certs/tls.crt"
      key_file: "/etc/nats/certs/tls.key"
      verify_and_map: false
      verify: false
    }

    websocket: {
      port: 8443
      no_tls: false
      same_origin: false
      allowed_origins ["*"]
      tls: {
        cert_file: "/etc/nats/certs/tls.crt"
        key_file: "/etc/nats/certs/tls.key"
        verify_and_map: false
        verify: false
      }
    }

    http_port: 8222
