apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-hub-nats-flapi-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dev-hub-nats-flapi-storage
  hostPath:
    path: /data/nats/dev
