apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-hub-nats-flapi-cert
  namespace: staging-hub-nats-flapi
spec:
  secretName: staging-hub-nats-flapi-tls
  dnsNames:
    - staging.hub-nats.flapi.org
    - staging.hub-nats-ws.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer