apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-hub-nats-flapi-cert
  namespace: prod-hub-nats-flapi
spec:
  secretName: prod-hub-nats-flapi-tls
  dnsNames:
    - hub-nats.flapi.org
    - hub-nats-ws.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer